name: Deploy to EC2 Docker
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Add SSH Key
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 600 key.pem
      - name: Deploy
        run:
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@rafaelhoyoiescamp.duckdns.org "cd /app && docker compose pull && docker compose up -d"
